/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "places-airports.h"
#include <iostream>
#include <iomanip>


airports_ret *
airports_qry_1_svc(location *argp, struct svc_req *rqstp)
{
	static airports_ret  result;

  std::cout << "Airports got a request lat: " 
            << argp->latitude << ", long: " << argp->longitude << std::endl;

  result.err = 0;

  std::cout << "done sleeping" << std::endl;

  auto& airports = result.airports_ret_u.results;
  for (int i = 0; i < 5; ++i) {
    airports[i].loc.latitude = 0.1;
    airports[i].loc.longitude = 0.2;
    airports[i].code = (char*)"abc";
    airports[i].name = (char*)"sample";
    airports[i].state = (char*)"WA";
    airports[i].dist = 0.3;
  }

  std::cout << "Returning result" << std::endl;
	return &result;
}
