/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PLACES-AIRPORTS_H_RPCGEN
#define _PLACES-AIRPORTS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct location_s {
	double latitude;
	double longitude;
};
typedef struct location_s location_s;

struct airport_record_s {
	location_s loc;
	char *code;
	char *name;
	char *state;
};
typedef struct airport_record_s airport_record_s;

struct airp_dist_t {
	airport_record_s airport;
	double distance;
};
typedef struct airp_dist_t airp_dist_t;

typedef struct {
	u_int airp_dist_recs_t_len;
	airp_dist_t *airp_dist_recs_t_val;
} airp_dist_recs_t;

struct airports_ret {
	int err;
	union {
		airp_dist_recs_t airports;
		char *error_msg;
	} airports_ret_u;
};
typedef struct airports_ret airports_ret;

struct places_result_s {
	char *place;
	airp_dist_recs_t airports;
};
typedef struct places_result_s places_result_s;

struct places_ret {
	int err;
	union {
		places_result_s result;
		char *error_msg;
	} places_ret_u;
};
typedef struct places_ret places_ret;

struct client_city_state_req_t {
	char *city;
	char *state;
};
typedef struct client_city_state_req_t client_city_state_req_t;

typedef client_city_state_req_t client_req_t;

#define PLACES_PROG 0x32215623
#define PLACES_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PLACES_QRY 1
extern  places_ret * places_qry_1(client_req_t *, CLIENT *);
extern  places_ret * places_qry_1_svc(client_req_t *, struct svc_req *);
extern int places_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PLACES_QRY 1
extern  places_ret * places_qry_1();
extern  places_ret * places_qry_1_svc();
extern int places_prog_1_freeresult ();
#endif /* K&R C */

#define AIRPORTS_PROG 0x32215624
#define AIRPORTS_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define AIR_QRY 1
extern  airports_ret * air_qry_1(location_s *, CLIENT *);
extern  airports_ret * air_qry_1_svc(location_s *, struct svc_req *);
extern int airports_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define AIR_QRY 1
extern  airports_ret * air_qry_1();
extern  airports_ret * air_qry_1_svc();
extern int airports_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_location_s (XDR *, location_s*);
extern  bool_t xdr_airport_record_s (XDR *, airport_record_s*);
extern  bool_t xdr_airp_dist_t (XDR *, airp_dist_t*);
extern  bool_t xdr_airp_dist_recs_t (XDR *, airp_dist_recs_t*);
extern  bool_t xdr_airports_ret (XDR *, airports_ret*);
extern  bool_t xdr_places_result_s (XDR *, places_result_s*);
extern  bool_t xdr_places_ret (XDR *, places_ret*);
extern  bool_t xdr_client_city_state_req_t (XDR *, client_city_state_req_t*);
extern  bool_t xdr_client_req_t (XDR *, client_req_t*);

#else /* K&R C */
extern bool_t xdr_location_s ();
extern bool_t xdr_airport_record_s ();
extern bool_t xdr_airp_dist_t ();
extern bool_t xdr_airp_dist_recs_t ();
extern bool_t xdr_airports_ret ();
extern bool_t xdr_places_result_s ();
extern bool_t xdr_places_ret ();
extern bool_t xdr_client_city_state_req_t ();
extern bool_t xdr_client_req_t ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PLACES-AIRPORTS_H_RPCGEN */
